# Generated by Django 3.2.5 on 2021-07-26 15:37

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Prenume')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nume')),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('residence', models.CharField(max_length=300, verbose_name='Current place of residence')),
                ('occupation', models.CharField(choices=[('Highschool Student', 'Highschool Student'), ('University Student', 'University Student'), ('Employee', 'Employee')], max_length=100)),
                ('languages_spoken', multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Romanian', 'Romanian'), ('Hungarian', 'Hungarian'), ('German', 'German'), ('French', 'French')], max_length=40, null='Not Added')),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('fb_link', models.URLField(blank=True, max_length=300, null=True)),
                ('departments', models.ForeignKey(null='Not Added', on_delete=django.db.models.deletion.CASCADE, to='hrm.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null='Not Added', on_delete=django.db.models.deletion.CASCADE, to='hrm.volunteer', verbose_name='Head Of Department'),
        ),
    ]
