# Generated by Django 3.2.5 on 2021-07-27 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_alter_volunteer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='departments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.department'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Prenume'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Nume'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='occupation',
            field=models.CharField(choices=[('Highschool Student', 'Highschool Student'), ('University Student', 'University Student'), ('Employee', 'Employee')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='residence',
            field=models.CharField(max_length=300, null=True, verbose_name='Current place of residence'),
        ),
    ]
