# Generated by Django 3.2.5 on 2021-07-27 20:52

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_auto_20210727_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.department'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='languages_spoken',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('English', 'English'), ('Romanian', 'Romanian'), ('Hungarian', 'Hungarian'), ('German', 'German'), ('French', 'French')], max_length=40, null='Not Added'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nume'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Highschool Student', 'Highschool Student'), ('University Student', 'University Student'), ('Employee', 'Employee')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='residence',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Current place of residence'),
        ),
    ]
