# Generated by Django 3.2.5 on 2021-07-28 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0005_auto_20210727_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contracte/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-user-image.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
