# Generated by Django 3.2.5 on 2021-08-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_auto_20210801_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='event',
            field=models.ForeignKey(null='Not Added', on_delete=django.db.models.deletion.CASCADE, to='hrm.event'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='volunteer',
            field=models.ForeignKey(null='Not Added', on_delete=django.db.models.deletion.CASCADE, to='hrm.volunteer'),
        ),
    ]
