# Generated by Django 3.2.5 on 2021-08-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0009_auto_20210804_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='occupation',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='fb_link',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Facebook Link'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_pic',
            field=models.ImageField(blank=True, default='files/default-user-image.png', null=True, upload_to=''),
        ),
    ]
