# Generated by Django 3.2.5 on 2021-08-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_auto_20210816_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='phone_number',
            new_name='telephone_number',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='fb_link',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='residence',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adress'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Birth Place'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='cnp_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True, verbose_name='CNP ID'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='county',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='County'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='domiciliu',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domiciliu'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='emitere_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Emitere Buletin'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='id_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date ID'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='nr_serie_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Number Serie ID'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='parents',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parents'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='seria_id',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Serie ID'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Last Name'),
        ),
    ]
