# Generated by Django 3.2.5 on 2021-08-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0012_legaltemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='profile_pic',
        ),
    ]
