# Generated by Django 3.2.5 on 2021-08-18 16:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0013_remove_volunteer_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresă'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data nașterii'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Locul nașterii'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='cnp_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True, verbose_name='Codul Numeric Personal'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Țară'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='county',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Județ'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Prenume'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='id_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dată emitere buletin'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nume'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='nr_serie_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True, verbose_name='Număr serie buletin'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='parents',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Părinți'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='seria_id',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Serie buletin'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='telephone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Număr de telefon'),
        ),
    ]
