# Generated by Django 3.2.5 on 2021-09-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0014_auto_20210818_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='nr_serie_id',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Număr serie buletin'),
        ),
    ]
