# Generated by Django 3.2.5 on 2021-09-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0015_alter_volunteer_nr_serie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(blank=True, null='No volunteers yet', to='hrm.Volunteer'),
        ),
    ]
